_target_: external_submodules.hptr.src.data_modules.data_h5_womd.DataH5womd

data_dir: ""
filename_train: training
filename_val: validation
filename_test: testing
n_agent: 64

batch_size: 3
num_workers: 4
